url: https://seb199510.github.io
baseurl: /hunnar/

# Site settings
title: Club Hunnar
email: your-email@domain.com
description: "Loge for særligt udvaglte individer med passion og talent for at skabe noget nyt og unikt."
future: true 

# Team names, titles and social links
people:
- name: DJ Klaes
  pic: 4
  position: Lead DJ
  social:
    #- title: twitter
    #  url: #
    #- title: facebook
    #  url: #
    - title: soundcloud
      url: https://soundcloud.com/dj-klaes

- name: Brumbrazz
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: King Theodon
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: JJ The Great
  pic: 5
  position: Lead Producer
  social:
    - title: youtube
      url: https://www.youtube.com/channel/UCDZRhDottMytwxcYsoHVLzQ
    - title: website
      url: https://jensjulius.com/
    - title: tiktok
      url: https://www.tiktok.com/@jensjulius_tejlgaard

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCDZRhDottMytwxcYsoHVLzQ
  - title: facebook
    url: https://www.facebook.com/dj.klaus.2024
    



# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
